site_name: MichaelBot Documentation

nav:
  - "Home": index.md
  - "Commands":
    - "Core": commands/core.md
    - "Dev": commands/dev.md
    - "Bot events": commands/events.md
    - "Experiment": commands/experiment.md
    - "Logging events": commands/logger.md
    - "Moderation": commands/moderation.md
    - "Music": commands/music.md
    - "Settings": commands/server.md
    - "Utility": commands/utility.md
  - "Templates":
    - "Menu": template/menu.md
    - "Paginator": template/paginator.md
    - "Help": template/help.md
  - "Utilities":
    - "Utility methods": utilities/methods.md

theme:
  name: "readthedocs"
