site_name: MichaelBot Documentation

repo_url: https://github.com/MikeJollie2707/MichaelBot
repo_name: MikeJollie2707/MichaelBot

theme:
  name: material
  font:
    text: Ubuntu
    code: Consolas
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      primary: deep purple
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      primary: teal
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - search.highlight

nav:
  - Home: index.md
  - Installation: INSTALLATION.md
  - Commands:
    - Bot: user/bot.md
    - Fun: user/fun.md
    - Logs: user/logger.md
    - Music: user/music.md
    - Utilities: user/utilities.md
  - Developer Corner:
    - errors.py: dev/errors.md
    - funtext.py: dev/funtext.md
    - help.py: dev/help.md
    - helpers.py: dev/helpers.md
    - models.py: dev/models.md
    - nav: dev/menu.md
    - psql.py: dev/psql.md

dev_addr: '127.0.0.1:8001'

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [..]
          options:
            show_root_toc_entry: false
            members_order: source
            docstring_style: numpy
            docstring_section_style: table
            show_source: true
            show_submodules: false
            separate_signature: false
            show_signature_annotations: true
            show_if_no_docstring: false

watch:
  - ../categories
  - ../utils