site_name: MichaelBot Documentation

nav:
  - "Home": index.md
  - "Installation": installation.md
  - "Commands":
    - "Core": commands/core.md
    - "Currency": commands/currency.md
    - "Dev": commands/dev.md
    - "Bot events": commands/events.md
    - "Game": commands/game.md
    - "Logging events": commands/logger.md
    - "Moderation": commands/moderation.md
    - "Music": commands/music.md
    - "NSFW": commands/nsfw.md
    - "Settings": commands/server.md
    - "Utility": commands/utility.md
  - "Templates":
    - "Menu": template/menu.md
    - "Paginator": template/paginator.md
    - "Help": template/help.md
  - "Utilities":
    - "Utility methods": utilities/methods_cog.md
    - "Database methods": utilities/db.md

theme:
  name: "material"
