site_name: MichaelBot Documentation

nav:
  - "Home": index.md
  - "Installation": installation.md
  - "Commands":
    - "Core": commands/core.md
    - "Currency": commands/currency.md
    - "Dev": commands/dev.md
    - "Bot events": commands/events.md
    - "Game": commands/game.md
    - "Logging events": commands/logger.md
    - "Moderation": commands/moderation.md
    - "Music": commands/music.md
    - "NSFW": commands/nsfw.md
    - "Settings": commands/server.md
    - "Utility": commands/utility.md
  - "Currency System":
    - "Intro": currency/currency_start.md
    - "Basic": currency/currency_basic.md
    - "Intermediate": currency/currency_intermediate.md
    - "Advanced": currency/currency_advanced.md
    - "Balance Changes": currency/balance_changes.md
  - "Templates":
    - "Help": template/help.md
    - "Menu": template/menu.md
    - "Paginator": template/paginator.md
  - "Utilities":
    - "Utility methods": utilities/facility.md
    - "Database methods": utilities/db.md

repo_url: https://github.com/MikeJollie2707/MichaelBot
repo_name: "MikeJollie2707/MichaelBot"

theme:
  name: "material"
  palette:
    scheme: slate
    primary: teal
    accent: cyan
  icon:
    repo: fontawesome/brands/github

# Use emoji
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
